name: Docker CI/CD voor Tracknote

on:
  push:
    branches:
      - main
      - beta

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Stel dynamische image tag in
        id: set_tag
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          IMAGE_BASE_NAME="ghcr.io/${{ github.repository }}"

          if [ "$BRANCH_NAME" == "main" ]; then
            TAG_VALUE="$IMAGE_BASE_NAME:latest"
          else
            TAG_VALUE="$IMAGE_BASE_NAME:$BRANCH_NAME"
          fi

          echo "full_tag=$TAG_VALUE" >> $GITHUB_OUTPUT
          echo "Geselecteerde tag: $TAG_VALUE"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in op GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Bouw en Push Docker image naar GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.set_tag.outputs.full_tag }}
